version: 2.1

jobs:
  # Lint job
  lint:
    working_directory: ~/repo
    docker:
      - image: csabasulyok/pnpm:8.10.0-node20-alpine
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: pnpm i
      - run:
          name: Run linters & compile
          command: pnpm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths:
            - '.'

  # Publish job
  publish:
    working_directory: ~/repo
    docker:
      - image: csabasulyok/pnpm:8.10.0-node20-alpine
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: pnpm i
      - run:
          name: Build package
          command: pnpm build
      - run:
          name: Publish to registry
          command: pnpm publish:npmjs

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths:
            - '.'

workflows:
  lint-and-publish-workflow:
    jobs:
      - lint
      - publish:
          context: npm-registry
          requires:
            - lint
          filters:
            branches:
              only: main
